### PR TITLE
Enable parent objects with no vertices to create Bounding Box

### PR DESCRIPTION
**Pull request by JehandadK**
Fix for issue #1774 

Opened pull request to get some guidance. For now only refactored code that search for min max points in Object3D's vertices.

### CODE REVIEW

**Comment by JehandadK** [comment]
The BoundingBox is a part of Geometry3D and not a part of Object3D, but creating a bounding box for an Object3D with no vertices requires access to its children. Should I consider 

- moving the bounding box to Object3D
OR
- give a public/package local setter for BoundingBox in Geometry3D.

**Comment by jwoolston** [comment]
> Should I consider
> 
> moving the bounding box to Object3D OR
> give a public/package local setter for BoundingBox in Geometry3D

Go with the setter on `Geometry3D`. Keep the visibility as low as possible.

**Comment by JehandadK** [comment]
Object3D can have the following cases

- It has vertices, in which case the bounding box was created fine
- It has no vertices but has children, and now it will create a bounding box correctly
- It has vertices as well as children. What should we do in this case? I dont know if this is valid opengl scenario.
- It has no vertices and no children, in which case getting the bounding box based on Maximum and minimum Double Values. I suggest returning a default Bounding Box in this case

**Comment by jwoolston** [comment]
> It has vertices as well as children. What should we do in this case? I dont know if this is valid opengl scenario.

This is valid, but somewhat undefined in the current Rajawali. I am working to clarify that moving forward. In the meantime, the bounding box should be based on both the object verticies and its children.



> It has no vertices and no children, in which case getting the bounding box based on Maximum and minimum Double Values. I suggest returning a default Bounding Box in this case

For various reasons, a box based on the min/max double values is appropriate so that the box essentially always intersects.

**Comment by JehandadK** [comment]
Tests working fine on my own app as well as examples.
device-2016-09-30-170122
device-2016-09-30-165759

**Comment by jwoolston** [comment]
Looks good to me. Thanks for taking this on.

**Pull request merged**
