### PR TITLE
Test for Github CI

### PR DESCRIPTION
**Pull request by hannesa2**
This PR changes nothing. 
It's only about to see, if Github action works properly

### CODE REVIEW

**Comment by ToxicBakery** [comment]
Screenshot from 2020-04-04 08-13-41
Let me know if you need anything else

**Comment by hannesa2** [comment]
Coll, thank you.
Even Espresso test are working !
But the Gradle verify action doesn't start

**Comment by hannesa2** [comment]
Hmm, even baumpfleger.yml doesn't work ?
I've to delete branch manually

**Comment by hannesa2** [comment]
This it the expectation, it should happen automatically
image

**Pull request closed without merging**
