### PR TITLE
fixed camera Z axis rotation issue

### PR DESCRIPTION
**Pull request by contriteobserver**
forgot to transpose the reflection matrix in my last checkin

resolves the rest of #1920

### CODE REVIEW

**Comment by jwoolston** [comment]
@contriteobserver What is the purpose of transposing the inverse view matrix? That seems suspect to me. Also, what is the reason for removing the normalization?

**Comment by contriteobserver** [comment]
the transpose changes the order of the reflection operations so the scaling is applied correctly, the normalization got the scaling right, but the order was wrong, once I saw it I removed the normalization in favour of the transpose.

**Comment by rami-dabain** [comment]
is this related? https://github.com/Rajawali/Rajawali/issues/1936

**Comment by contriteobserver** [comment]
@rami-dabain this issue is unrelated to #1936, the title was an attempt at a simple description of a complex concept, namely that the reflection looked odd when the geometry emphasised the effects of non-uniform scaling, i.e. when the camera was rotated on multiple axes. The second normalisation vs transpose is really a uniform vs non-uniform scaling issue. It is easy to see when you know what you are looking for, but the visual effect is difficult to describe.

**Pull request merged**
