### PR TITLE
Delay count wasn't set to 0 when reset() was called.

### PR DESCRIPTION
**Pull request by MasDennis**

### CODE REVIEW

**Comment by ToxicBakery** [comment]
This was intentional, reset is only intended to halt the animation and rewind its elapsed animation time. You'll notice that none of the other fields are reset either like reverse, repeat count, etc. 

For clarity the controls are intended be timeline oriented with play, pause, stop, reset all intended to relate with time not features.

**Comment by ToxicBakery** [comment]
Nvm my previous message, I should drink coffee to avoid looking like an idiot. Carry on.

**Comment by MasDennis** [comment]
Or maybe a beer instead of a coffee? It is almost 5 o'clock in Armenia.

**Comment by ToxicBakery** [comment]
beer isn't for another 5 hours when its 6 o'clock here.

**Pull request merged**
