### PR TITLE
Fix for Issue #1355 -- Animated GIF & Alpha Channel.

### PR DESCRIPTION
**Pull request by Jaben**
Clears before drawing the canvas to support transparent GIFs.

### CODE REVIEW

**Comment by Jaben** [comment]
Low hanging fruit. :)

**Comment by jwoolston** [comment]
Looks like you might have forgotten to commit the include line for Color. Can you fix this and push to the same branch?

**Comment by Jaben** [comment]
Sorry about that...

**Comment by jwoolston** [comment]
Ok looks good. Merging.

**Comment by jwoolston** [comment]
@Jaben Thanks for the fix!

**Comment by Jaben** [comment]
@jwoolston you're welcome! Thank you for Rajawali!

**Pull request merged**
