### PR TITLE
#1595 Adds cardboard integration (which now includes 3d audio).

### PR DESCRIPTION
**Pull request by jwoolston**
Signed-off-by: Jared Woolston <jwoolston@tenkiv.com>

### CODE REVIEW

**Comment by rpicolet** [comment]
This is an FYI, _not_ urgent. 

After a fresh pull from Rajawali master, the AS build fails on my machine with this error:

>Error:(1, 1) A problem occurred evaluating project ':examples'.
     > Failed to apply plugin [id 'com.android.application'] 
              > Gradle version 2.10 is required. Current version is 2.8. If using the gradle wrapper, try editing the distributionUrl in /Users/Randy/Code/AS/Rajawali/gradle/wrapper/gradle-wrapper.properties to gradle-2.10-all.zip

which is weird since that is exactly the version in the properties file.  

From the command line, `./gradlew build` reports no problems, everything seems to build OK.

Not sure it's a valid test, but when I replaced 
`classpath 'com.android.tools.build:gradle:2.1.0-alpha1'`
with 
`classpath 'com.android.tools.build:gradle:1.5.0'`
in the project build.gradle file, the AS build got past the gradle version problem, but failed with the messages here:

[Rajawali build error.txt](https://github.com/Rajawali/Rajawali/files/178604/Rajawali.build.error.txt)

Since this PR was the commit that changed the plugin version, I thought I'd report it here in case it was related.

Also, yesterday I updated my AS SDK tools to 23.0.2, and NDK bundle to 11.0.0.

Probably some combination of unstable configurations...

**Comment by jwoolston** [comment]
Yeah, i had seen the exact same combination of errors. in my case using 2.1.0-alpha1 is the only thing that fixed it. I honestly have no idea whats going on but apparently it isnt "fixed". Thanks for the info.

**Comment by rpicolet** [comment]
Let me know if you want me to try anything on my machine.

Ain't the bleeding edge just so much fun!

**Comment by jwoolston** [comment]
> Ain't the bleeding edge just so much fun!

Haha, yea. Normally I avoid it. I have been shying away from that version of the plugin all this time. I only thought to try it because @MasDennis who originally updated the VR integration had used it. When it fixed the build problems I assumed there was some obscure need for it (probably with the other SDK updates). Can you try using the as in master version (alpha) and delete your build folders then tell AS to rebuild the project?

**Comment by rpicolet** [comment]
> Can you try using the as in master version (alpha) and delete your build folders then tell AS to rebuild the project?

I think you're asking me to do a clean rebuild with the `gradle:2.1.0-alpha1` Android plugin?  Assuming that, I verified the plugin version in `build.gradle`, manually deleted the `build` folders under each module, and then invoked Rebuild Project from the menu.

From Rajawali/build.gradle:
```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.0-alpha1'
    }
}
```
From gradle/wrapper/gradle-wrapper.properties:
```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-2.10-all.zip
````

Same result:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/Randy/Code/AS/Rajawali/examples/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':examples'.
> Failed to apply plugin [id 'com.android.application']
   > Gradle version 2.10 is required. Current version is 2.8. If using the gradle wrapper, try editing the distributionUrl in /Users/Randy/Code/AS/Rajawali/gradle/wrapper/gradle-wrapper.properties to gradle-2.10-all.zip

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.247 secs
```
If you wanted something else, just lemme know

**Comment by jwoolston** [comment]
No, clean is too stupid to figure out the issue. Literally go into the vr, rajawali and examples modules and delete the folders named "build". Then go to Build->Rebuild Project

**Comment by rpicolet** [comment]
>I verified the plugin version in build.gradle, manually deleted the build folders under each module, and then invoked Rebuild Project from the menu.

Yeah, that's what I did ;-)

**Comment by jwoolston** [comment]
Yes I see, sorry I must have missed that. Well then I'm not sure what the issue is yet.

**Comment by rpicolet** [comment]
Minor discovery, I can get rid of the gradle version problem by changing the AS setting in:
```
Preferences->Build, Execution, Deployment->Build Tools->Gradle 
```
to
```
Use default Gradle wrapper (recommended)
```
which then shows a problem finding thd DSL for compile()...

**Comment by jwoolston** [comment]
What version of AS do you use out of curiosity.

**Comment by rpicolet** [comment]
I just updated to 1.5.1 before my last post.

And now I also see that the message has a little more data:
```
Error:(36, 1) A problem occurred evaluating project ':examples'.
> Could not find method compile() for arguments [com.android.support:appcompat-v7:23.2.0] on DefaultExternalModuleDependency{group='com.android.support', name='support-v13', version='23.2.0', configuration='default'}.
```
The `version='23.2.0'` sticks out like a sore thumb, since I just installed SDK tools 23.0.2, but that may just be a concidence.

**Comment by jwoolston** [comment]
Yea that's just coincidence. 23.2.0 is the latest version of the support libraries. If you return to version 1.5.x of the plugin and clear the build folders out does anything change?

**Comment by jwoolston** [comment]
Sorry to run you around, I only have version 2.x of AS installed so I'm trying to get a feel of what might be going on

**Comment by rpicolet** [comment]
> If you return to version 1.5.x of the plugin and clear the build folders out does anything change?

No, same result as above (referencing the support lib) running with Android plugin 1.5.0. 
> Sorry to run you around, I only have version 2.x of AS installed so I'm trying to get a feel of what might be going on

No problem, having different configs is why I offered

**Comment by jwoolston** [comment]
What about checking out a version of the repository before this PR? Does everything just automagically go back to working right?

**Comment by rpicolet** [comment]
Its weird that the command line build still works; along with the test above, that kind eliminates the plug-in as the culprit
>What about checking out a version of the repository before this PR? Does everything just automagically go back to working right?
So like git checkout <commit number>?

**Comment by jwoolston** [comment]
Well if the command line build is fine than thats it. AS 1.5 probably cant use the 2.x plugin.

**Comment by jwoolston** [comment]
> So like git checkout ?

It doesnt need to be a full checkout from the server, just checkout that commit or create a branch from that commit.

**Comment by rpicolet** [comment]
>Randys-MacBook-Pro:Rajawali Randy$ git status
HEAD detached at 3bc6c2b
nothing to commit, working directory clean
Randys-MacBook-Pro:Rajawali Randy$ 

Build works fine,

**Comment by rpicolet** [comment]
So should I upgrade to AS 2.x?

**Comment by jwoolston** [comment]
Ok so that confirms its some combination of AS and the gradle plugin. Some more looking on SO suggests that there may be some version checking bugs between the latest plugins and latest versions of AS (1.5.1 vs 2.x). When you were on master HEAD and trying the 1.5.x version of the android plugin, did you ever try 1.5.1?


> So should I upgrade to AS 2.x?

I'm not going to make a hard recommendation here. I use it daily for my personal stuff as well as my day job and everything works fine for my needs. I don't use instant run because it is still deceptively unreliable and I find it makes it hard to be certain your changes have made it over. Beyond that, I have no complaints, however it is still in Alpha/Beta depending on which version you choose.

**Comment by rpicolet** [comment]
>When you were on master HEAD and trying the 1.5.x version of the android plugin, did you ever try 1.5.1?

No, 1.5.0.  When I tried 1.5. just now, AS (1.5.1) couldn't find it:

>Error:Could not find com.android.tools.build:gradle:1.5.1.
Searched in the following locations:
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/android/tools/build/gradle/1.5.1/gradle-1.5.1.pom
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/android/tools/build/gradle/1.5.1/gradle-1.5.1.jar
    https://jcenter.bintray.com/com/android/tools/build/gradle/1.5.1/gradle-1.5.1.pom
    https://jcenter.bintray.com/com/android/tools/build/gradle/1.5.1/gradle-1.5.1.jar
Required by:
    :Rajawali:unspecified

**Comment by jwoolston** [comment]
Hmmm, still no go with 1.5.0 for me either. I have no idea what about the vr module caused all this. Im still fiddling with things to try and figure out whats going on.

**Comment by rpicolet** [comment]
I'm co-installing the 2.0 Beta 7, I'll let you know how it turns out...

**Comment by jwoolston** [comment]
> I'm co-installing the 2.0 Beta 7, I'll let you know how it turns out

Sounds good.

**Comment by jwoolston** [comment]
As an aside, this should only affect Rajawali development, not its use.

**Comment by rpicolet** [comment]
Yep, I figure its a great way to learn what all the issues/challenges are.  I've been learning a huge amount in the last couple of weeks, and it tastes good. :beers:

**Comment by rpicolet** [comment]
Happy happy, beta 7 works great, build and run examples!
Makes sense, need AS 2.x to run plugin 2.x...

**Comment by rpicolet** [comment]
Cardboard looks great!

**Comment by jwoolston** [comment]
Good to hear. Yea @MasDennis made a pretty nice demo there

**Pull request merged**
