### PR TITLE
Adds wear support

### PR DESCRIPTION
**Pull request by jwoolston**
#1595 Adds a wear library and example project.

### CODE REVIEW

**Comment by ToxicBakery** [comment]
I think you need to add `- extra-google-m2repository` in the components section of travis to get the wear dependencies.

**Comment by jwoolston** [comment]
> I think you need to add - extra-google-m2repository in the components section of travis to get the wear dependencies.

https://github.com/Rajawali/Rajawali/blob/master/.travis.yml#L15

Already there.

**Comment by ToxicBakery** [comment]
No that is the android m2 not the google m2

**Comment by jwoolston** [comment]
:sigh: why cant they just put the damn things in jcenter.

**Comment by ToxicBakery** [comment]
You and everyone else wants to know why too. It's really bloody annoying the update tool is garbage and you are forced to use it.

**Pull request merged**
