### PR TITLE
AWD skeletal animation parsing

### PR DESCRIPTION
**Pull request by gormanb**
Adds AWD skeletal animation parsing, along with a couple of fixes. Developed using an AWD version of the boblampclean MD5 model and a few other simple test models. There is some relatively minor but noticeable distortion of the models during animation, but unfortunately I won't have time in the near future to pin this down.

### CODE REVIEW

**Comment by jwoolston** [comment]
Looks good. I have pinned down the issue with the mirroring/rotation, now I'm just trying to figure out a fix.

**Comment by jwoolston** [comment]
Thanks again @gormanb

**Comment by gormanb** [comment]
No problem @jwoolston. Now if you'll excuse me it's 4:15am here, time to pass out :smile:

**Comment by MasDennis** [comment]
Thanks @gormanb great work! Can't wait to try it out.

**Pull request merged**
