### PR TITLE
attempt to fix CircleCI

### PR DESCRIPTION
**Pull request by hannesa2**
This is a test drive if my [change](https://github.com/Rajawali/RajawaliDocker/pull/2) fix the CI [issue](https://circleci.com/gh/Rajawali/Rajawali/108?utm_campaign=chatroom-integration&utm_medium=referral&utm_source=slack).
As soon as a new tag exists here https://hub.docker.com/r/rajawali/rajawali/tags I can move to this

### CODE REVIEW

**Comment by hannesa2** [comment]
But unfortunately current CI settings don't build PR 
image

**Comment by hannesa2** [comment]
I'm not familiar with CircleCI, does someone knows what to do in [config.yml](https://github.com/Rajawali/Rajawali/blob/master/.circleci/config.yml), to build PR as well ?

**Comment by hannesa2** [comment]
Here I see no build of this PR too
https://circleci.com/gh/Rajawali/Rajawali

but prior PR's were build ?

image

**Comment by ToxicBakery** [comment]
We can't build external pull requests for security reasons unfortunately. The change you made to docker should resolve the issue though once you update the config to use the latest image.

**Comment by hannesa2** [comment]
Hmm ? Your [link](https://cloud.docker.com/u/rajawali/repository/docker/rajawali/rajawali/builds/4d4a84f4-9a05-498a-a8dc-bc88a7f3d840) shows me this
image

**Comment by ToxicBakery** [comment]
hmm guess it's private. I'll tag that image though for you so you can use it. Forgot that's a require step.

**Comment by hannesa2** [comment]
I see new tag `latest` here https://hub.docker.com/r/rajawali/rajawali/tags

**Comment by hannesa2** [comment]
I moved to `latest`

**Comment by ToxicBakery** [comment]
right, I just tagged the docker repo so give it probably 20-30 minutes to build and it should update to the latest tag which has your api 29 change in it. We can't use `latest` given that makes it difficult to know exactly which docker image was used to build the project at a given time.

**Comment by ToxicBakery** [comment]
looks like the image built. if you replace your previous commit with 1.1 it should work

**Comment by hannesa2** [comment]
done, it's now 1.1

btw
> We can't use `latest` given that makes it difficult to know exactly ...

Total agreement, but when I would maintain my own project, I would go `api29`, because nobody knows why it's a `1.1`. But it's only to find a name for the baby and you are the parents

**Comment by ToxicBakery** [comment]
That's a fair argument, I'll think about that for future tags

**Pull request merged**
