### PR TITLE
PR for #1607 - combining object color picking and post-processing

### LINKED ISSUE #1607: Combining object color picking and post-processing
[This ticket originated from discussions after #1586 was closed; this post is a partial copy from there.]

...

It's probably better to start by nailing down the basic goals/requirements. I propose that these are:
* to allow all 4 combinations of the two features to inter-operate reliably: default rendering, default rendering plus color picking, post-processing, and post-processing plus color-picking.
* to better isolate the very different "never visible" color-picking GL render details from those of the "visible" renders, and so make it easier to test/maintain both, and to add new features to either
* to minimize changes to the client API for both features,
* within reason, to maximize code re-use and minimize the code footprint

I'll wait to get some feedback on these goals before doing anything more on this. I should say, even if most everyone agrees with these as the goals, I haven't really yet thought of an approach that accomplishes all of them well, so getting some sense of relative priorities would also help me a lot in proposing a design.

...

### PR DESCRIPTION
**Pull request by rpicolet**
Fixes #1607 

## Change Summary
* Scene.java
 * added `doColorPicking()` to isolate color-picking render from normal render() control flow
 * renamed `requestColorPickingTexture()` to `requestColorPicking()` 
* Object3D.java
 * introduced `UNPICKABLE` color/index, made it a default value
 * updated `setPickingColor()`, removed `getPickingColor()`
 * eliminated `mIsPickingEnabled`, now check for `UNPICKABLE`
 * added `renderColorPicking()` for optimized/independent color-picking rendering of the `Object3D` and its children (per #1387)
* ObjectColorPicker.java
 * updated `unregisterObject()` to reset picking color to UNPICKABLE
 * renamed `createColorPickingTexture()` to `pickObject()`
 * in `pickObject()` call to `GLES20.glReadPixels()`, replaced `getDefaultViewportHieght()` with `getViewportHeight()`

## Testing:
* Examples: Object Picking, Touch & Drag now work, and all other examples appear to work same as on master branch
* Picking nested child objects: working on my app...
* Combined color-picking && post-processing: I quickly cut/paste the GreyScale Filter setup into the Object Picking example; monkeys are rendered grey, but seem to have `y = viewportHeight - y`; picking then appears to work as if screen was rendered correctly (e.g. picking the upper left monkey moves the lower left monkey, and vice versa). I can't think of any way the object picking could interfere with the filter renders before anything is even picked, so I think this may be a post-processing-only issue masked by the random nature of the objects in the post-processing examples (which therefore have no natural sense of up/down that would easily reveal the same behavior).

## Concerns
* I was pretty aggressive in optimizing the color-picking rendering methods;
 * setup blending and depth testing just once at the scene level
 * at the object level, eliminated matrix updates, checks/setups for textures, normals, vertex colors, etc.
* I'd really appreciate some more experienced eyes desk-checking my changes and optimizations.  One nice thing here is that if something needs to change, it (probably) _shouldn't_ affect any of the non-color-picking renders
* Haven't really thought about threading/concurrency issues. Probably needs to be e.g. a sync lock on references to `mPickingInfo` in `Scene.requestColorPicking()` and `Scene.render()`?

Any/all questions/suggestions welcome, as usual...

### CODE REVIEW

**Comment by rpicolet** [comment]
Oh, forgot, BTW. Touch & Drag seems to miss a lot of picks, I think it may be because it's using wireframes for the pickable objects, so the exact touch coordinates may well miss all of the wires...

**Comment by jwoolston** [comment]
Working on this tonight.

**Comment by jwoolston** [comment]
> I think it may be because it's using wireframes for the pickable objects, so the exact touch coordinates may well miss all of the wires

You are correct. If you want to update the examples to render triangles as part of this PR that would be great, otherwise I can do it separately.

**Comment by rpicolet** [comment]
>You are correct. If you want to update the examples to render triangles as part of this PR that would be great, otherwise I can do it separately.

OK, I'll give it a shot...

**Comment by jwoolston** [comment]
Should just be a change from `GLES20.GL_LINE_LOOP` to `GLES20.GL_TRIANGLES`

**Comment by jwoolston** [comment]
@rpicolet can you add or post an example of color picking with post processing. I added greyscale to the object picking as well and I see post processing working, but not object picking, so I am curious what we did differently

**Comment by jwoolston** [comment]
> monkeys are rendered grey, but seem to have y = viewportHeight - y

I believe this is related to the issues with texture coordinates on the screen quad. We should keep this in mind, but leave it to something else to fix. There is already an issue open along these lines: #1561

**Comment by rpicolet** [comment]
> can you add or post an example of color picking with post processing

Hmm, couldn't upload as .java.. Go figure.

Anyway, all I did was cut and paste the lines from GreyScale Filter that create/populate `mEffects`, and then called `mEffects.render()` in `onRender()` instead of `super.onRender()`...

[ObjectPickingFragment.txt](https://github.com/Rajawali/Rajawali/files/177136/ObjectPickingFragment.txt)

**Comment by jwoolston** [comment]
Hmmm, mine looks identical to yours and I cant seem to get it to work (its grey, but no object picking)

**Comment by rpicolet** [comment]
>Should just be a change from GLES20.GL_LINE_LOOP to GLES20.GL_TRIANGLES

That did it, updated the push.

**Comment by jwoolston** [comment]
> Although they now just look like 2D circles... maybe need some lighting change?

Up to you. I think its fine but If you want to add a directional light to the scene that should work fine.

**Comment by rpicolet** [comment]
> Hmmm, mine looks identical to yours and I cant seem to get it to work (its grey, but no object picking)

It's unreliable. I have to poke around a lot to find just the right spots that trigger picking...

**Comment by jwoolston** [comment]
> It's unreliable. I have to poke around a lot to find just the right spots that trigger picking

Hmmm, yes I have noticed the same...seems worth figuring out, though I am not sure if it needs to be fixed here as this does accomplish the initial goal of fixing color picking, including children.

**Comment by rpicolet** [comment]
>Hmmm, yes I have noticed the same...seems worth figuring out, though I am not sure if it needs to be fixed here as this does accomplish the initial goal of fixing color picking, including children.

Maybe we should just see if we can get the problem to occur without color-picking?

Your call, I'm OK either way.

**Comment by rpicolet** [comment]
I just did a quick test, added the first ObjectPIcking  monkey (upper left) to the GreyScale FIlter, and it shows up upside down in the lower left, so that pretty much nails it...

**Comment by jwoolston** [comment]
So further inspection suggests there is some sort of a problem here. I pulled down the entire FrameBuffer  into bitmaps in the debugger and got the following results:

## Normal Color Picking
plain_color_picking

## Color Picking with Greyscale PostProcess
post_processing_picking

The checkerboard in the plain one is to show that the color is transparent (low picking index). As you can see, in the example with post processing, nothing shows in the frame buffer.

**Comment by rpicolet** [comment]
Not at all sure how the framebuffer stuff works, but I'm pretty convinced the problem is not my PR changes.
]

**Comment by jwoolston** [comment]
> but I'm pretty convinced the problem is not my PR change

I agree, they didn't introduce anything. Mostly I want to find out how these two interact. I suspect the fact that more than 1 framebuffer is involved is part of it.

**Comment by rpicolet** [comment]
So, anything else you would like me to do of this? perhaps the sync lock on mPickingInfo? testing other feature combinations?  

BTW, in my app, my touch objects are double-sided transparent panels, so I think that kinda covers a couple more feature integration points...

**Comment by jwoolston** [comment]
Yes, in theory transparency or materials in general should have no effect on this so that is good to hear for confirmation. 

Rather than synchronizing, lets declare it volatile and add a @NonNull annotation to the `requestColorPicking()` method parameter. This saves the overhead of synchronizing while still accomplishing the same result. We don't really care if someone changes the picking info at any time, so long as we are certain every read of it is the most up to date. Adding the non-null annotation defines in the contract that the user cannot set it to null, ensuring it wont become null between our null check and its use. Technically, the user could still do so by breaking the contract, but I am not worried about defensively coding the engine to the point that we start adding extra stuff just to make sure someone doesn't do something against the API.

**Comment by jwoolston** [comment]
once you do that, Ill merge it and track down this issue with the FBOs seperately

**Comment by rpicolet** [comment]
> ...lets declare it volatile and add a @NonNull annotation to the requestColorPicking() method parameter. 

Makes sense. Just because I'm a pedantic pain, I'll point out that there is also a small chance that a second pick could theoretically occur between `doColorPicking(mPickerInfo)` and `mPickerInfo = null` but I seriously doubt the user would be able to tell if it gets ignored so close to the first pick. Will do as you suggest, and will also make ColorPickerInfo immutable just to be a bit safer.

As far as API abuse goes, I would think client apps should really only be coming through the ObjectColorPicker.getObjectAt() method anyway.  Kinda gets at the documentation challenge again.  Maybe a good place to start would be (for some kind, knowledgeable person with lots of time on their hands) to define the supported API calls as interfaces, and just say if ain't in the published IScene or whatever, it ain't supported. Coming someday real soon now!

**Comment by jwoolston** [comment]
> (for some kind, knowledgeable person with lots of time on their hands) to define the supported API calls as interfaces, and just say if ain't in the published IScene or whatever, it ain't supported.

Yes, this is something I have done in a private fork of Rajawali at my employer. It helps considerably with reducing the visibility of API calls for sure. Unfortunately that work is not compatible with merging into the main rajawali repository. It is a fine goal though and I will gladly accept PRs on the issue, provided they are thoughtfully explained of course. I have been making efforts to move in that direction with abstractions of things like ISurfaceRenderer and the like.

**Pull request merged**
