### PR TITLE
UV orientation in ScreenQuad primitive now matches that of Plane.

### PR DESCRIPTION
**Pull request by contriteobserver**
fixes Tilted camera images on the ScreenQuad #1850

### CODE REVIEW

**Comment by jwoolston** [comment]
Thanks @contriteobserver. I have dealt with this myself but never got around to fixing it.

**Comment by rpicolet** [comment]
I think I was the last one to touch those coordinates. Prior to my  change, u used `1.0 - u` and v used `1.0 - v`, but while testing the combination of color picking with postprocessing effects, I changed the v coordinate (to just `v`, not `1.0 - v`) to get everything working.  So if this is now the correct mapping, there may be some other places where things need to also change, maybe the color picking glReadpixels call (it uses the flipped version for y, i.e. `viewport.height - y`), and/or somewhere in postprocessing.  But I really don't understand all the coordinate mapping choices here and throughout the library yet, and how they are supposed to work together.

**Comment by jwoolston** [comment]
> But I really don't understand all the coordinate mapping choices here and throughout the library yet, and how they are supposed to work together.

They are a mess and I don't want to deal with them unless someone pays me to. Our 2.0 work should take care of it.

**Comment by jwoolston** [comment]
#1852

**Pull request merged**
