### PR TITLE
added ability to set skybox geometry

### PR DESCRIPTION
**Pull request by contriteobserver**
addresses issues raised in #1904
also partially cleans up skybox implementation

### CODE REVIEW

**Comment by contriteobserver** [comment]
1) Meant reflections or environment mapping of objects, not cameras, sorry.
2) Was trying to leave existing practice (700 and 1000) intact, while addressing #1959 for those in need. 
3) Using median diameter, not media radius.

**Comment by rpicolet** [comment]
1) I won't pretend to understand theses use cases or their issues, I believe you.

2) Oh, I missed that you intended the new setSkybox(Cube, ATexture) as a new API.  I see how that can work, and even though it makes the app responsible for texture construction, it can be used to get the job done.  Did you consider instead using a setSkyboxSize() method (that replaces the underlying Cube object) that could work with the existing setSkybox()/updateSkybox() methods, and/or adding set/update wrappers with a size parameter?  Any reason not to add something similar later on (e.g. in 2.0)?

3) Also missed that you switched variable/name to "diameter" after computing the two radii, and so could skip the divide by 2. OTOH I'm guessing the extra distance provided by adding the internal radius solves granularity issues with perspective division at large depths?  I always wondered why it was set all the way out to 1000 for a skybox of 700 with an outer radius (of 350 time root 3 =) 610 or so...  

Thanks again for all your user support!

**Comment by contriteobserver** [comment]
Settled on the setSkyBox(Cube, ATexture) for a variety of reasons:
- addresses issues in #1904 
- provides high level API that satisfies most users, and a low level API for those that need it
- locates all skybox creation to a single function (later raised in #1959)
- allows environment maps and skybox to share the same texture.

**Comment by rpicolet** [comment]
Got it, makes sense, thanks for the insights.

**Comment by TBog** [comment]
Can we also have this method?
`	/**`
`	 * Set the skybox using the provided Cube.`
`	 * It is expected to have a material set and the material to have at least a texture.`
`	 *`
`	 * @return {@code boolean} True if the provided cube passes the requirements`
`	 */`
`	public boolean setSkybox( Cube cube )`
`	{`
`		if ( cube == null )`
`			return false;`
`		Material mat = cube.getMaterial();`
`		if ( mat == null || mat.getTextureList().isEmpty() )`
`			return false;`
`		synchronized ( mNextSkyboxLock )`
`		{`
`			mNextSkybox = cube;`
`			mSkyboxTexture = mat.getTextureList().get( 0 );`
`		}`
`		return true;`
`	}`

**Comment by contriteobserver** [comment]
Part of the intent was to funnel all the `setSkybox()` methods through a single function. Why is `setSkyBox(final Cube skybox, final ATexture texture)` problematic for setting custom materials?

**Comment by contriteobserver** [comment]
Part of the original intent was to funnel all the Skybox texture updates through a single method. If we are to support custom materials for Skyboxes, it seems best to make it a first class feature for all the texture update methods. That way, a custom material would survive texture updates. Thoughts?

**Comment by jwoolston** [comment]
Skyboxes as they are now basically only support diffuse textures. I can think of situations where more than this would be desired, but I think in the situation people should be in their own with updates as it will be rare. To this end I think all the texture methods applying to the normal material is fine if we just add a method which takes a material as an argument.

**Comment by contriteobserver** [comment]
We also need to think about Environment maps, so custom skybox materials are properly reflected. It will take a little while to postulate how they can be effectively associated.

**Comment by jwoolston** [comment]
Good point. That far exceeds the scope of this pr so I will merge. Those issues can be addressed later.

**Pull request merged**
